import { LoginPage } from "./login"

    const a=new LoginPage()
    it('Create account',function(){
        cy.visit('https://itera-qa.azurewebsites.net/')
        
        a.clickSignUp()
        a.enterFirstName('raj')
        a.enterSurname('iragamreddy')
        a.enterMobileNumber('9381150555')
        a.enterUserName('rajKumar')
        a.enterPassword('Rajkumar123')
        a.enterConfirmPassword('Rajkumar123')
        a.clickOnSubmit()
    })
it('validCredentials',function(){
    cy.visit('https://itera-qa.azurewebsites.net/')
    
    /*a.clickSignUp()
    a.enterFirstName('raj')
    a.enterSurname('iragamreddy')
    a.enterMobileNumber('9381150555')
    a.enterUserName('rajKumar')
    a.enterPassword('Rajkumar123')
    a.enterConfirmPassword('Rajkumar123')
    a.clickOnSubmit()*/
    a.logo()
    a.clickOnLogin()
    a.enterUserName('rajKumar')
    a.enterPassword('Rajkumar123')
    a.clickOnLogin1()
    a.clickOnLogOut()
})
it('invalidUserName',function(){
    cy.visit('https://itera-qa.azurewebsites.net/')
    a.logo()
    a.clickOnLogin()
    a.enterUserName('yhnfbn')
    a.enterPassword('Rajkumar123')
    a.clickOnLogin1()
    cy.get('.alert-danger').should('exist')
})
it('invalidPassword',function(){
    cy.visit('https://itera-qa.azurewebsites.net/')
    a.logo()
    a.clickOnLogin()
    a.enterUserName('rajKumar')
    a.enterPassword('oknujnd')
    a.clickOnLogin1()
    cy.get('.alert-danger').should('exist')
})
it('BlankUserName',function(){
    cy.visit('https://itera-qa.azurewebsites.net/')
    a.logo()
    a.clickOnLogin()
    a.enterUserName(' ')
    a.enterPassword('Rajkumar123')
    a.clickOnLogin1()
    cy.get('.alert-danger').should('exist')
})
it('BlankPassword',function(){
    cy.visit('https://itera-qa.azurewebsites.net/')
    a.logo()
    a.clickOnLogin()
    a.enterUserName(' ')
    a.enterPassword('Rajkumar123')
    a.clickOnLogin1()
    cy.get('.alert-danger').should('exist')
})

it('Login',function(){
    cy.visit('https://itera-qa.azurewebsites.net/')
    a.logo()
    a.clickOnLogin()
    a.enterUserName('rajKumar')
    a.enterPassword('Rajkumar123')
    a.clickOnLogin1()
    cy.get('#searching').should('exist')
})
it('Creating customer details',function(){
    cy.visit('https://itera-qa.azurewebsites.net/')
    a.logo()
    a.clickOnLogin()
    a.enterUserName('rajKumar')
    a.enterPassword('Rajkumar123')
    a.clickOnLogin1()
    cy.get('#searching').should('exist')
    a.clickOnCreate()
    a.enterNameForCreatingCustomer('anil')
    a.enterCompanyName('QualiTlabs')
    a.enterAdress('gachibowli,hyderabad')
    a.enterCityName('Hyd')
    a.enterPhoneNumber('123444445')
    a.enterEmail('asdf@gmail.com')
    a.clickOnCreateForCustomer()
    cy.get('[href="/Customer/Create"]').should('exist')
    
    cy.get('input[name="searching"]').type('anil')
    cy.get('input[type="submit"]').click()
})
it('Checking all the modules present or not',function(){
    cy.visit('https://itera-qa.azurewebsites.net/')
    a.logo()
    a.clickOnLogin()
    a.enterUserName('rajKumar')
    a.enterPassword('Rajkumar123')
    a.clickOnLogin1()
    cy.get('#searching').should('exist')
    cy.get('[href="/"]').should('exist')
    cy.get('[href="/home/practice"]').should('exist')
    cy.get('[href="/home/automation"]').should('exist')
    cy.get('[href="/home/tutorial"]').should('exist')
})
it('Content of each module',function(){
    cy.visit('https://itera-qa.azurewebsites.net/')
    a.logo()
    a.clickOnLogin()
    a.enterUserName('rajKumar')
    a.enterPassword('Rajkumar123')
    a.clickOnLogin1()
    cy.get('#searching').should('exist')
    cy.get('[href="/"]').should('exist')
    cy.get('[href="/home/practice"]').should('exist')
    cy.get('[href="/home/automation"]').should('exist')
    cy.get('[href="/home/tutorial"]').should('exist')
    cy.get('[href="/"]').click()
    cy.get('img[alt="Test"]').should('exist')
    cy.get('[href="/home/practice"]').click()
    cy.get('.card-body').should('exist')
    cy.get('[href="/home/automation"]').click()
    cy.get('.display-3').should('exist')
    cy.get('[href="/home/tutorial"]').click()
    a.clickOnLogOut()
})