export class LoginPage{
    logo(){
        cy.get('img[alt="Itera logo"]').should('exist')
    }
    clickSignUp(){
        cy.get('[href="/UserRegister/NewUser"]').click()
    }
    enterFirstName(FirstName){
        cy.get('#FirstName').type(FirstName)
    }
    enterSurname(surname){
        cy.get('#Surname').type(surname)
    }
    enterMobileNumber(mobileNumber){
        cy.get('#Mobile').type(mobileNumber)
    }
    enterUserName(userName){
        cy.get('input[name=Username]').type(userName)
    }
    enterPassword(password){
        cy.get('#Password').type(password)
    }
    enterConfirmPassword(confirmPassword){
        cy.get('#ConfirmPassword').type(confirmPassword)
    }
    clickOnSubmit(){
        cy.get('input[type=submit]').click()
    }
    clickOnLogin(){
        cy.get('a[href="/Login"]',{timeout:5000}).click()
    }
    clickOnLogin1(){
        cy.get('input[type="submit"]').click()
    }
    clickOnLogOut(){
        cy.get('[href="/Login/LogOut"]').click()
    }
    clickOnCreate(){
        cy.get('[href="/Customer/Create"]').click()
    }
    enterNameForCreatingCustomer(name){
            cy.get('#Name').type(name)
    }
    enterCompanyName(companyName){
        cy.get('#Company').type(companyName)
    }
    enterAdress(adress){
        cy.get('#Address').type(adress)
    }
    enterCityName(cityName){
        cy.get('#City').type(cityName)
    }
    enterPhoneNumber(phoneNumber){
        cy.get('input[name="Phone"]').type(phoneNumber)
    }
    enterEmail(email){
        cy.get('input[name="Email"]').type(email)
    }
    clickOnCreateForCustomer(){
        cy.get('input[type="submit"]').click()
    }

}